server:
  port: 8761

spring:
  application:
    name: registry

security:
  basic:
    enabled: true               #  开启基于HTTP basic的认证
  user:
    name: ${REGISTRY_SERVER_USERNAME}
    password: ${REGISTRY_SERVER_PASSWORD}

eureka:
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 20
    lease-renewal-interval-in-seconds: 10
  client:
    registerWithEureka: false
    fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0

cola:
  swagger2:
    enable: true
    base-package: com.honvay.cola
    title : Cola-Cloud
    description: Cola cloud Restful API docs
    termsOfServiceUrl : http://localhost:4000
    version: 1.0
    apiName: Authorization
    apiKeyName: Authorization