spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
  profiles:
     active: native
  application:
    name: configser

eureka:
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 20
    lease-renewal-interval-in-seconds: 10
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}:${spring.application.name}
  client:
    registry-fetch-interval-seconds: 10
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://admin:123456@registry:8761/eureka/

server:
  port: 8888

security:
  basic:
    enabled: true               #  开启基于HTTP basic的认证 
  user:
    name: config                  # 配置登录的账号是
    password: 123456           # 配置登录的密码是
